DROP TABLE IF EXISTS [groups];
CREATE TABLE [groups] (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name STRING UNIQUE
);
	
DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname STRING
);
	
DROP TABLE IF EXISTS students;
CREATE TABLE students (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	fullname STRING,
	group_id REFERENCES [groups] (id)
);

DROP TABLE IF EXISTS subjects;
CREATE TABLE subjects (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name STRING,
	teacher_id REFERENCES teachers (id)
);

DROP TABLE IF EXISTS rates;
CREATE TABLE rates (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	student_id REFERENCES student (id),
	subject_id REFERENCES subject (id),
	rate INTEGER,
	date_of DATE
	);
